### PR TITLE
Update Mirrorz + 6 new plugin proposals

### PR DESCRIPTION
**Pull request by zwaba**
Update Mirrorz + 6 new plugin proposals

2 for the delay category: 
STUTTTER ( a Double Stutter effect (L/R) with even and odd time division)
and 
COZMIC ( a 4 asynchronous delay lines plugin inspired by “Cosmos” as requested by a forum user)

4 small utility plugins :
Zinvert_phase a simple phase inverter
Ztoggle4   Toggle one in → 4 outs
Xfade1to2st  crossfade input to two outs
Toggle_2IN  a switchbox CV assignable.

### CODE REVIEW

**Comment by zwaba** [comment]
Ok, I did the DisthroPluginfo files, put the .ttl files in the custom.ttl folder and added a folder with the modgui’s…but without success, I’m afraid I need help.

**Comment by falkTX** [comment]
finally I updated these on the repo, but I am missing some files,
first are the modgui.ttl for each plugin, then the whole modgui for the mirrorz plugin.
can you upload these? doesnt have to be here even, wherever is the most convenient for you.

**Comment by zwaba** [comment]
Hi Filipe,
Here are all the modgui.ttl and modgui 's folder.LES MODGUis.zip


| 
| 
|  | 
LES MODGUis.zip


 |

 |

 |




Best regards
Jph
    Le mercredi 20 décembre 2023 à 12:22:28 UTC+1, Filipe Coelho ***@***.***> a écrit :  
 
 


finally I updated these on the repo, but I am missing some files,
first are the modgui.ttl for each plugin, then the whole modgui for the mirrorz plugin.
can you upload these? doesnt have to be here even, wherever is the most convenient for you.

**Comment by falkTX** [comment]
that didnt seem to have worked. you can try sending directly to falktx@mod.audio as email, attachments via github replies seem to get lost..

**Comment by falkTX** [comment]
modguis are in place now, at least on this repo.

image

the mirrorz plugin needs quite some attention to its graphics, it does not really fit the plugin.

and we need to come up with a better way to push new plugins and updates, for this one there was quite some setup on my side which doesn't scale.
ideally the pull requests from your side already come with all the files ready to go.
for now I added some very basic rules on the readme file of this repo, still to be extended significantly.

for now should I push these to beta then?

**Comment by falkTX** [comment]
also, closing this PR since the files are in the repo now

**Pull request closed without merging**
